"""added attendance_date column and renamed date to marked_at

Revision ID: 8bc14eed80cd
Revises: ac4a82364f1d
Create Date: 2026-05-02 01:03:44.029578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc14eed80cd'
down_revision: Union[str, Sequence[str], None] = 'ac4a82364f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('attendance_date', sa.Date(), nullable=True))
    op.add_column('attendance', sa.Column('marked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('attendance', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True))
    op.drop_column('attendance', 'marked_at')
    op.drop_column('attendance', 'attendance_date')
    # ### end Alembic commands ###
